### ISSUE TITLE
Attention model fix?

### ISSUE THREAD

**Issue by user06039** [mmehdig/seq2seq-attention-model#3]
Thanks for this wonderful notebook. Are there any future plans to update and fix the attention model. It's just that there aren't any good attention model implementation in keras out there.

**Comment by mmehdig** [comment]
Yeah thanks, I guess I have to do something about this... since there are interests for it :)
I have a repository of tutorials for vision and language. There, I have left a few lines of comments in the model definition for attention model, it might be interesting for you:
https://github.com/mmehdig/apl-esslli-19-material/blob/master/3-language-models-part2/train_flickr30k_captions.ipynb

**Comment by user06039** [comment]
@mmehdig Thanks I'll check it out. It's really really hard to find any good implementations of attention seq2seq models out there. If you in case come across any then it will be either outdated (or) doesn't work. There are hundreds of question regarding where to find any good attention implementation on StackOverflow that are still un-answered. If you do work on it please implement a bahdanau attention on Bi-LSTM  with machine translation example using keras similar to current notebook in the repo. I'll be happy to help regarding this you just let me know. It be really beneficial to many students like me out there.
